// <auto-generated />
namespace KitchenEquipmentManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class remove_registered : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_registered));
        
        string IMigrationMetadata.Id
        {
            get { return "202507201121180_remove_registered"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
